from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Float

Base = declarative_base()

class GradeData(Base):
    __tablename__ = 'grades'
    id = Column(Integer, primary_key=True)
    A_plus = Column('A+',Float)
    A = Column(Float)
    A_minus = Column('A-', Float)
    B_plus = Column('B+', Float)
    B = Column(Float)
    B_minus = Column('B-', Float)
    C_plus = Column('C+', Float)
    C = Column(Float)
    C_minus = Column('C-', Float)
    D_plus = Column('D+', Float)
    D = Column(Float)
    D_minus = Column('D-', Float)
    F = Column(Float)
    Pass = Column(Float)
    Not_Pass = Column('Not Pass', Float)
    Satisfactory = Column('Satisfactory', Float)
    Unsatisfactory = Column(Float)
    Not_Satisfactory = Column('Not Satisfactory', Float)
    Incomplete = Column(Float)
    In_Progress = Column('In Progress', Float)
    Withdrawn = Column(Float)
    Withdrawn_Passing = Column('Withdrawn Passing', Float)
    Withdrawn_Medical = Column('Withdrawn Medical', Float)
    Withdrawn_Incomplete = Column('Withdrawn Incomplete', Float)
    Drop = Column(Float)
    Withdrawn_from_University = Column('Withdrawn from University', Float)
    Honors = Column(Float)
    No_Grade = Column('No Grade', Float)
    Review = Column(Float)
    Audit = Column(Float)
    Not_Reported = Column('Not Reported', Float)
    Repeat = Column(Float)
    DFWU = Column(Float)
    Pending_Judicial_Action = Column('Pending Judicial Action',Float)
    Withheld = Column(Float)
    Report_In_Progress = Column(Float)
    I_RD_RP = Column('I,RD,RP',Float)
    wo_I_RD_RP = Column('w/o I RD RP', Float)  
    # Adjusted the variable name and corrected 'Column'
    # Add the rest of the grade columns here in a similar fashion
    instructor = Column(String)
    year = Column(Integer)
    catalog_number = Column('Catalog Number', String)
    subject = Column(String)
    term = Column(String)
    university = Column(String)
    title = Column(String)
    GPA = Column(Float)
